global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'zine'
    static_configs:
      - targets: ['localhost:5000']

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
