version: '3.4'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"

  eventstoredb:
    image: eventstore/eventstore:21.2.0-buster-slim
    container_name: eventstore
    hostname: eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
  
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"

  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserverdb
    hostname: sqlserverdb
    environment:
      - SA_PASSWORD=Teste@S3nha
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  postgresdb:
    image: postgis/postgis
    container_name: postgresdb
    hostname: postgresdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Teste@S3nha
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  webapi-tests:
    container_name: webapi-tests
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - .:/src
      - ../tests:/tests
    working_dir: /src
    command: [
      "dotnet",
      "test",
      "../tests/Argon.Zine.App.Api.Tests/Argon.Zine.App.Api.Tests.csproj"
    ]
    environment:
      - ConnectionStrings__IdentityConnection=Server=sqlserverdb;Database=Identity;User Id=sa;Password=Teste@S3nha;
      - ConnectionStrings__CustomerConnection=Server=postgresdb;Database=Customer;User Id=admin;Password=Teste@S3nha;
      - ConnectionStrings__RestaurantConnection=Server=postgresdb;Database=Restaurant;User Id=admin;Password=Teste@S3nha;
      - ConnectionStrings__CatalogConnection=Server=sqlserverdb;Database=Catalog;User Id=sa;Password=Teste@S3nha;
      - ConnectionStrings__OrderingConnection=Server=postgresdb;Database=Ordering;User Id=admin;Password=Teste@S3nha;
      - ConnectionStrings__EventSourcingConnection=ConnectTo=tcp://admin:changeit@eventstore:1113
      - ConnectionStrings__CatalogRedis=reids:6379
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - sqlserverdb
      - postgresdb
      - mongodb
      - eventstoredb