version: '3.4'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
       
  mongo-express:
    image: mongo-express
    container_name: mongo-express 
    depends_on:
      - mongodb

  mongodb-exporter:
    container_name: mongodb-exporter
    image: percona/mongodb_exporter:0.30

  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver

  argon.zine.app.api:
    image: ${DOCKER_REGISTRY-}argonzineappapi
    container_name: webapi
    hostname: webapi
    build:
      context: .
      dockerfile: Apps/Argon.Zine.App.Api/Dockerfile
    depends_on:
      - sqlserverdb
      - mongodb
      - postgresdb
      - eventstore
      - rabbitmq
      - redis

  eventstore:
    image: eventstore/eventstore:21.2.0-buster-slim
    container_name: eventstore
    hostname: eventstore

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    hostname: rabbitmq

  redis:
    image: redis
    container_name: redis
    hostname: redis

  redismanager:
    image: lukiya/redismanager
    container_name: redismanager
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - argon.zine.app.api

  loki:
    image: grafana/loki:2.3.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
  
  postgresdb:
    image: postgis/postgis
    container_name: postgresdb
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgresdb

  jaeger: 
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    hostname: jaeger