global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'zine'
    static_configs:
      - targets: ['host.docker.internal:5000']

  - job_name: prometheus
    static_configs:
      - targets: ['host.docker.internal:9090']
