name: Chat Service

on:
  push:
    branches: [ main ]
  
    pahts:
    - src/BuildingBlocks/**
    - src/Services/Chat/**
    - tests/Argon.Zine.Chat.Tests/
    - .github/workflows/chat-service.yml

  pull_request:
    branches: [ main ]

    pahts:
    - src/BuildingBlocks/**
    - src/Services/Basket/**
    - tests/Argon.Zine.Basket.Tests/
    - .github/workflows/basket-service.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test ./tests/Argon.Zine.Chat.Tests/ --no-build --verbosity normal