name: Identity Service

on:
  push:
    branches: [ main ]
  
    pahts:
    - src/BuildingBlocks/**
    - src/Services/Identity/Argon.Zine.Identity/**
    - tests/Argon.Zine.Identity.Tests/
    - .github/workflows/identity-service.yml

  pull_request:
    branches: [ main ]

    pahts:
    - src/BuildingBlocks/**
    - src/Services/Identity/Argon.Zine.Identity/**
    - tests/Argon.Zine.Identity.Tests/
    - .github/workflows/identity-service.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test ./tests/Argon.Zine.Identity.Tests/ --no-build --verbosity normal