name: Zine API
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Run integration tests
        run: docker-compose -f .\docker-compose.staging.yml up --build --abort-on-container-exit